apiVersion: apps/v1
kind: Deployment
metadata:
  name: netrelay
spec:
  selector:
    matchLabels:
      app: netrelay
  template:
    metadata:
      labels:
        app: netrelay
        instance: tradfri
    spec:
      nodeSelector:
        location: bentrup
      containers:
      - name: netrelay
        image: ghcr.io/xanecs/netrelay:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 5684
          protocol: UDP
          name: coaps
        - containerPort: 5683
          protocol: UDP
          name: coap
        env:
        - name: NETRELAY_CONFIG
          value: /config/relay.json
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
      - name: config
        configMap:
          name: netrelay-config