namespace: netrelay
resources:
- rbac.yaml
- deployment.yaml
configMapGenerator:
- name: netrelay-config
  files:
  - relay.json
secretGenerator:
- name: tailscale-auth
  literals:
  - AUTH_KEY=${AUTH_KEY}